### ISSUE TITLE
Fix solver upload mechanism in benchmax

### ISSUE THREAD

**Issue by nafur** [smtrat/smtrat#10]
As of now, `benchmax` simply pushes the solver binaries to the computation nodes into the home folder of the user.
This can fail in a variety of way:
- The filename could already be taken (for example by a folder `smtrat`)
- Two solvers could have the same name (but different folder, that is stripped before uploading)
- The solver could be dynamically linked and then lacking it's libraries. This works on our blades due to the shared home folders, but may fail in the wild.

**Comment by derjasper** [comment]
Implemented chagnes as suggested by @nafur 
The dependency resolution can be enabled by the --ssh.resolvedeps option
