### ISSUE TITLE
Dynamic theory variable order

### ISSUE THREAD

**Issue by smtrat** [smtrat/smtrat#18]
Make variable order dynamic in MCSAT.

- Treat theory variables exactly like Boolean variables? Or adapt how bumping works?
- Are Boolean and theory conflicts the same? Bump all variables in both cases?

**Comment by smtrat** [comment]
SMT-Assignmentfinder: k-lookahead does nor work because the variable order is no longer available.

**Comment by smtrat** [comment]
order_heap: save non-decidable variable in some list that is restored after T-Decide. Try to allow decisions on any univariate variable, not only on "in the next theory variable univariate" variables (as it is not clear which theory variable is the next one...)

**Comment by smtrat** [comment]
Bookkeeping no longer has mVariableOrdering but only mAssignedVariables. Backends can no longer rely on having a full variable ordering.

- NLSAT / OneCell: construct *any* variable ordering compatible with the already assigned variables
- FM / VS: no changes necessary

**Comment by derjasper** [comment]
Implement T-Backjump-Decide rule
