### ISSUE TITLE
The type of produce-models should be "bool" but is "carl::Formula

### ISSUE THREAD

**Issue by Heizmann** [smtrat/smtrat#2]
I run [smtrat 2.1.0](https://github.com/smtrat/smtrat/files/306722/smtrat_linux64.zip) on the 
[attached SMT script](https://github.com/smtrat/smtrat/files/382703/InVarSynth_GasCakeWithJohoFractions01.bpl_Iteration2.smt2.txt) and obtained the following error message.

```
(error "The type of produce-models should be "bool" but is "carl::Formula<carl::MultivariatePolynomial<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, carl::MonomialComparator<&carl::Monomial::compareGradedLexical, true>, carl::StdMultivariatePolynomialPolicies<carl::NoReasons, carl::NoAllocator> > >".")
unknown
```

**Comment by nafur** [comment]
Added a simplify step to allow smtlib attributes to be simplified from formulas to bools. This fixes the above issue.
