### ISSUE TITLE
Make optimization compatible with variable elimination

### ISSUE THREAD

**Issue by nafur** [smtrat/smtrat#25]
Right now, optimization usually crashes as soon as some module (e.g. FPPModule) eliminates a variable that is involved in the objective function. Unfortunately the objective function is represented as an equality and thus always allows to eliminate something...

We either need to disallow eliminating using the objective function (how? we do not know which equality it is once the Manager has added it. Also it seems incredibly hacky / ugly / suboptimal), or make our handling of objectives compatible with that (for example, objectives may change within a strategy)

**Comment by nafur** [comment]
One specific issue:
When optimizing, we run the backend and get the model [here](https://github.com/smtrat/smtrat/blob/1a081298a65031bea354be9cdcd991c1931639f0/src/smtrat-modules/SATModule/SATModule.cpp#L501) without checking whether the backend actually returned SAT. It might also return UNSAT and we should handle this case gracefully (retrieve infeasible subset, add it, continue with next assignment)

**Comment by nafur** [comment]
Another specific issue:
updateModel uses getBackendsModel [here](https://github.com/smtrat/smtrat/blob/1a081298a65031bea354be9cdcd991c1931639f0/src/smtrat-modules/SATModule/SATModule.cpp#L691) to obtain the model of the backend. This of course assumes that the backend model is in a state that allows for this call, i.e. that the last call returned SAT. This assumption may be wrong if we are optimizing. We should instead (at least when optimizing) store the model after every (SAT-) call and reuse the stored model here.

**Comment by nafur** [comment]
Another (less) specific issue:
The objective(s) are stored globally (in the Manager) right now. This is a problem when a module wants to change them, for example because a variable is eliminated (ESModule). I'd argue that simply disallowing eliminating variables (that occur in the objective function) is not a great idea.

We could instead avoid storing the polynomial in the Manager and only store the objective variable there.  
I would guess that we can do everything with the objective variable instead of the objective polynomial/function as well.

Still, a module may never eliminate the objective variable.

**Comment by derjasper** [comment]
The comments regarding handling of the optimal model are still an issue:
* https://github.com/smtrat/smtrat/issues/25#issuecomment-505066989
* https://github.com/smtrat/smtrat/issues/25#issuecomment-505067755
