### ISSUE TITLE
MaxSMT does not interact with preprocessing

### ISSUE THREAD

**Issue by nafur** [smtrat/smtrat#28]
All modules (except the MaxSMT module) ignore soft constraints.
This may become a problem if a preprocessing module eliminates a variable (but does not eliminate it from the soft constraints).

Attention: we can not naively eliminate it from the soft constraints!
(a) multiple soft constraints may become identical and we need to adapt the weights.
(b) What about incrementality by (push) and (pop)? We need to be able to backtrack these changes, which is hard if we simply change them in the manager...

**Comment by derjasper** [comment]
MaxSMT is now moved outside the Manager, so it is not affected by preprocessing anymore
