### ISSUE TITLE
Support for echo command

### ISSUE THREAD

**Issue by Heizmann** [smtrat/smtrat#4]
I just applied to most recent version 8dd6e395ee125d6c95f86a70ba9a1b65b9a22516 of smtrat to
[the attached script](https://github.com/smtrat/smtrat/files/440596/echo.smt2.txt) and obtained the following error message.
```
ERROR smtrat.parser: Parsing error at 9:1
ERROR smtrat.parser: expected
        eoi: <eoi>
ERROR smtrat.parser: but got
        (echo "Start declaration of constants")
ERROR smtrat.parser: in line 9
        (echo "Start declaration of constants")
Parse error
```
I would like to use smtrat in our software verifier [Ultimate Automizer](http://ultimate.informatik.uni-freiburg.de/automizer/). At the moment, our tool need support for the echo command which is defined in Section 4.2.9 of the [SMT-LIB 2.5 standard](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.5-r2015-06-28.pdf).

**Comment by nafur** [comment]
Is just added this. As of 057e577, `(echo ...)` should be supported as described in the SMT-LIB standard.
