### ISSUE TITLE
Segment fault on empty formula

### ISSUE THREAD

**Issue by rainoftime** [smtrat/smtrat#62]
Hi, for the following formula
~~~~
(set-logic QF_LRA)
(pop 1)
~~~~

smtrat (commit 3f50332) throws a segment fault

**Comment by nafur** [comment]
This is not a valid smt2 file, as for `(pop n)`, `n` needs to be smaller than the number of assertion levels on the stack (see 4.2.2 of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf). Nevertheless, we should give an error here, and not simply segfault...

**Comment by nafur** [comment]
Gives a proper error message as of 9d1a9ec6c9a3ab2882955d8fc4e4e003cf0ddab6.
