### ISSUE TITLE
Segment fault at UnivariatePolynomial.h:156

### ISSUE THREAD

**Issue by rainoftime** [smtrat/smtrat#63]
Hi, for the following formula,
~~~~
(set-logic QF_LIA)
(push 1)
(pop 1)
~~~~

smtrat (commit 97e3c340) throws a seg fault

**Comment by rainoftime** [comment]
Seem caused by UnivariatePolynomial.h:156

**Comment by nafur** [comment]
Also handled by 55fd1c4ce94d2810003220ec852ef438bf78774f.
