### ISSUE TITLE
Soundness issue on QF_NIA formula (mcsat)

### ISSUE THREAD

**Issue by rainoftime** [smtrat/smtrat#80]
Hi, for the following formula,

smtrat (commit 97e3c34) default mode gives `unsat',
but MCSATOC gives "sat".
~~~~
(set-logic QF_NIA)
(declare-fun i0 () Int)
(declare-fun i1 () Int)
(assert (or (and (= (* i1 i1) 889) (>= i0 35)) false))
(check-sat)
~~~~

**Comment by nafur** [comment]
Please stop submitting issues if you don't know what you are doing. Our MCSAT does not support integers.
