### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by abol-karimi** [smtrat/smtrat#93]
On `make smtrat-shared` I get the error:

`In file included from smtrat/src/smtrat-strategies/config.h:3:0,
                 from smtrat/src/smtrat-strategies/smtrat-strategies.h:6,
                 from smtrat/src/cli/smtratSolver.cpp:17:
smtrat/src/smtrat-strategies/strategies/RatComp2016.h:18:10: fatal error: smtrat-modules/CADModule/CADModule.h: No such file or directory
 #include <smtrat-modules/CADModule/CADModule.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by derjasper** [comment]
The default strategy was an old one which is broken. I changed the default strategy in cbbbd3b7d36e45bfdff149683405509356ddf457 
You might need to delete your build directory and run cmake again, or change the strategy to SMTCOMP in cmake manually.
